[package]
name = "labview"
version = "0.1.0"
authors = ["Steven Pease <peasteven@gmail.com>"]

[dependencies]
chrono = "0.4"
env_logger = "0.4"
log = "0.3"
num = "0.1"
serde_derive = "1.0"
serde = "1.0"
strum = "0.8"
strum_macros = "0.8"
